title: <p align="center"> Siddhant Srivastava </p>
logo: /assets/img/Siddhant.jpg
description:
  <p align="center">
  <a href="pdf/Siddhant Srivastava.pdf">Resume</a> |
  <a href="https://github.com/srivastavaSid">GitHub</a>
 
  <br>  
  I'm working as a CAD Engineer in Emulation & FPGA Domain.
  <br>
  </p>


theme: jekyll-theme-minimal